name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Install'
        required: true
        default: 'Test'

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        # run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        run: echo "${{ github.ref }} and ${{ github.event.input.environment }}"
        env:
          First_Name: Mona
